baseURL = 'http://complexecolab.github.io/'
languageCode = 'en-us'
title = 'Complex Ecology Systems Lab'
theme = 'cleanwhite'



[params]
  header_image = "img/homepage.gif"
  addtional_menu = "test"


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'People'
  url = '/people'
  weight = 20
[[menu.main]]
  name = 'Research'
  url = '/research'
  weight = 30
[[menu.main]]
  name = 'Publications'
  url = '/publications'
  weight = 40
[[menu.main]]
  name = 'Join us'
  url = '/joinus'
  weight = 50
