baseURL: http://complexecolab.github.io/
languageCode: 'en-us'
title: 'Complex Ecological Systems Lab'
theme: 'cleanwhite'

params:
  header_image: img/homepage.gif

menu:

  main:
    - name: 'Join us'
      url: '/joinus'
      weight: 50
    - name: 'People'
      url: '/people'
      weight: 20
    - name: 'Research'
      url: '/research'
      weight: 30
    - name: 'Publications'
      url: '/publications'
      weight: 40
